### ISSUE TITLE
Assess to webpack compilation object in postcss config context

### ISSUE THREAD

**Issue by kisenka** [webpack-contrib/postcss-loader#354]
I writing postcss plugin which produce extra asset (svg sprite) and need ability to write this asset to webpack's output file system. In 0.x versions of this loader it was feature when you can access loader object itself  (`webpack` context property of postcss config). Using this, postcss plugins for instance can write assets directly to webpack compilation object, but [it was removed](https://github.com/postcss/postcss-loader/commit/0dceb2c2dc827306533e44017e537d1862084c1a#diff-168726dbe96b3ce427e7fedce31bb0bcL72). I suggest following:

* Postcss plugin generate message with new type "asset"
* If loader find such message it creates file in webpack compilation

Example

**some-postcss-plugin.js**
```js
function plugin() {
  return (tree, result) => {

    // do stuff...

    result.messages.push({
      type: 'asset',
      file: 'sprite.svg',
      content: '<svg>...</svg>',
      plugin
    });
  }
}
```

**postcss-loader**
```js
if (msg.type === 'asset' && msg.content && msg.file) {
  this._compilation.assets[msg.file] = {
    source() { return msg.content; },
    size() { return msg.content.length; }
  };
}
```

I will be glad to make PR with this feature!

**Comment by evilebottnawi** [comment]
@michael-ciniawsky looks like we break plugins which emit assets. I think we should return this behaviour

**Comment by michael-ciniawsky** [comment]
I like the idea, but need more info about exact requirements here. @kisenka could you share a small demo project ?

> ⚠️ `this._compilation` is also deprecated so we need to ensure that e.g `this.emitFile` or adding the asset directly to `module.assets` works/is sufficient

**Comment by evilebottnawi** [comment]
@kisenka friendly ping
