### ISSUE TITLE
Remove ident property from options in docs

### ISSUE THREAD

**Issue by aorinevo** [webpack-contrib/postcss-loader#388]
### Type

- [x] Other

### Details

In the documentation, the examples sometimes add `ident` property to options.  Since webpack 2.2.1, this is no longer needed (see https://github.com/webpack/webpack/releases/tag/v2.2.1).

Also need to update test cases that use ident.

### Location

- [x] README

**Comment by michael-ciniawsky** [comment]
I was also under the impression that it shouldn't be necessary anymore as I initially open the issue about it in the webpack repo and asked if a unique `ident` could be assigned by default to every loader instead, without the need to manually specify it. The reality though is that there where still plenty of reports where `postcss-loader` stopped working when the custom `ident` was missing. So I'm inclined to still better leave it within the docs for now

**Comment by aorinevo** [comment]
I did see that in the closed issues.  Do you plan to drop support in v3?

**Comment by michael-ciniawsky** [comment]
If v3 is refering to `postcss-loader` then nope since it has already been released :). There isn't really anything to drop, besides removal from the docs. There was never been any PR made to webpack which fixed or refactored the logic for `ident`. I'm pretty sure it will still doesn't 💯 work
