### ISSUE TITLE
Cascade config loading provokes unwanted behaviour with npm link 

### ISSUE THREAD

**Issue by 779g** [webpack-contrib/postcss-loader#422]
When a linked package from `npm link` is used, the postcss config is searched for into the link tree and not the local one.

Let's imagine we have this two npm repos we're working on 
+ `custom-css-library` at `path/to/custom-css-library`, which is published on npm with the same name
+ `some-js-app` at `another-path/some-js-app`
We have a postcss config file at `some-js-app/postcss.config.js` which sould apply to any post-css processing happening with a local entrypoint (as per the docs https://github.com/postcss/postcss-loader#config-cascade)

We want to use `custom-css-library` in `some-js-app` without having to republish / reinstall every time custom-css-library changes so we do
```
cd path/to/custom-css library && npm link
cd another-path/some-js-app && npm install custom-css-library && npm link custom-css-library
``` 
(per the docs: https://docs.npmjs.com/cli/link.html)

After the base postcss with sass on webpack, we get

```
    ERROR in ./custom-css-library/main.scss (./node_modules/css-loader/dist/c
js.js!./node_modules/postcss-loader/src!./node_modules/sass-loader/dist/cjs.js!./node_modules/custom-css-library/main.scss)
    Module build failed (from ./node_modules/postcss-loader/src/index.js):
    Error: No PostCSS Config found in: some-js-app/node_modules/custom-css-library
```

Instead, wouldn't we expect to have `some-js-app/postcss.config.js` loaded ?, Maybe by appending by default the base  folder  where webpack is executed in the `$PATH` that the loader looks for the config file in ?

**Comment by evilebottnawi** [comment]
Now you can set absolute path to config (not directory), it should solve the problem, anyway if you still have a problem, please provide reproducible test repo, loading logic inside `cosmiconfig` package, so we can't manage it, maybe you need open the issue inside `cosmiconfig`, other solution is creating own utils for loading configuration, it is out of scope `postcss-loader`
