### ISSUE TITLE
Confusing plugins syntax

### ISSUE THREAD

**Issue by simonh1000** [webpack-contrib/postcss-loader#423]
### Type

- [ ] Other
- [ ] Wrong
- [x] Unclear
- [ ] Missing

### Details

the readme provides an example of a `postcss.config.js` with plugins as an object. On the main tailwind site, plugins is a list, so it is impossible to know how to combine the advice

### Location

- [x] README
- [ ] LICENSE
- [ ] CHANGELOG
- [ ] ISSUE_TEMPLATE
  - [ ] BUG
  - [ ] DOCS
  - [ ] FEATURE
- [ ] PULL_REQUEST_TEMPLATE

**Comment by evilebottnawi** [comment]
I don't understand problem

**Comment by simonh1000** [comment]
sorry, this was not really your problem I suppose. Tailwind provide an example of postcss.config.js that is an array, whereas you show an object. It is not at all obvious to a first timer like me how to reconcile the difference. Striclty speaking it is really tailwind's issue that they advise using your package but provide instructions that can't be used with it, but perhaps you could make the distinction clearer between the list and object notation on your site?

**Comment by evilebottnawi** [comment]
@simonh1000 Can you provide a link on their instructions?

**Comment by simonh1000** [comment]
https://tailwindcss.com/docs/installation#webpack

**Comment by evilebottnawi** [comment]
Now we support `Array` and `Object` syntax for plugins in `postcss.config.js` and `options.plugins`, also `tailwindcss` update docs, we will update docs too before the next major release
