### ISSUE TITLE
Allow setting fallback config for files that we can't find a config for.

### ISSUE THREAD

**Issue by aero31aero** [webpack-contrib/postcss-loader#432]
### Proposal

Allow specifying a fallback config, in case we cannot find a config for a file by looking up the tree.

The current system of specifying a config as below is not enough because we lose the ability to override this config via per-directory config files:

```js
{
    test: /\.scss$/,
    include: resolve(__dirname, '../static/styles'),
    use: [
        {
            loader: 'postcss-loader',
            options: {
                config: {
                    path: 'postcss.config.js',
                },
                sourceMap: true,
            },
        },
    ],
},
```

### Use Case

- `node_modules` is symlinked to a cached/versioned directory, so importing a css file from node_modules throws the error about not finding a postcss config.
- We have 2 postcss configs to use in the project, one at project root, and another for a subdirectory.
- setting `config` option in webpack config hardcodes all configs to the specified file.

### Implementation

- [ ] I'm open to work on this
- [ ] I need help/mentorship
- [x] I'm unable to work on this

I think an additional `falback: boolean` option would do the trick:

```js
// options
{
    config: {
        path: '...',
        fallback: true, // Default: false
    },
},
```

The final algorithm could be:

```js
get_config = (file, opts) => {
    const cascading_config = get_config_from_tree(file);
    const default_config = get_config_from_options(opts);

    if (!default_config && !cascading_config) throw Error("no config");
    if (!opts.config.fallback) return default_config;
    if (!cascading_config) return default_config;
    return cascading_config;
};
```

**Comment by aero31aero** [comment]
Related issue: https://github.com/postcss/postcss-loader/issues/293

**Comment by evilebottnawi** [comment]
Sorry, out of scope `postcss-loader`, you can implement own logic for loading config files

**Comment by evilebottnawi** [comment]
```
{
    test: /\.scss$/,
    include: resolve(__dirname, '../static/styles'),
    use: [
        {
            loader: 'postcss-loader',
            options: {
                config: {
                    path: getConfig() || '/path/to/default/postcss.config.js',
                },
                sourceMap: true,
            },
        },
    ],
},
```

**Comment by aero31aero** [comment]
That could work too. But I still think that either https://github.com/postcss/postcss-loader/issues/422 should be fixed or this should be added.

Thanks for the suggestion.

**Comment by evilebottnawi** [comment]
We use `postcss-load-config` module for loading configuration, so we can't do here something

**Comment by evilebottnawi** [comment]
Closing, future the `config` option will accept only: 
- `true` - autoload config
- `false` - do not autoload config
- `path/to/config.js` - path to config

If you need complex logic you can use `config: 'path/to/my-complex-configuration-builder.js'`
