### ISSUE TITLE
Setting plugins in Webpack instead of config file not working

### ISSUE THREAD

**Issue by michaelalhilly** [webpack-contrib/postcss-loader#455]
- Operating System: Mac OS Catalina 10.15.6
- Node Version: 12.18.3
- NPM Version: 6.14.6
- webpack Version: 4.44.1
- postcss-loader Version: 3.0.0
- postcss-preset-env Version: 6.7.0

### Expected Behavior

Use post-css-loader and postcss-preset-env without postcss.config.js. I would rather not pollute my project with unnecessary config files if possible.

### Actual Behavior

Following this project's docs I tried 3 different methods and none worked.

#### 1. Setting config property to false yields an error

```
{
    test: /\.styl$/,
    use: [
      {loader: mini_css.loader},
      {loader: "css-loader"},
      {
        loader: "postcss-loader",
        options: {
          config: false,
          postcssOptions: {
            plugins: (_) => [  require("postcss-preset-env")() ],
          },
        },
      },
      {loader: "stylus-native-loader", options: {}}
    ]
}
```

This yields the following error:
ValidationError: PostCSS Loader Invalid Options
options.config should be {Object} (https://github.com/postcss/postcss-loader#config)

The following documentation says config accepts a boolean:

https://drive.google.com/file/d/1iVLhiq7eIusqXtAJuSS0Uz8A4X6hS763/view?usp=sharing

### 2. Using plugins property to set postcss-preset-env yields an error

```
{
    test: /\.styl$/,
    use: [
      {loader: mini_css.loader},
      {loader: "css-loader"},
      {
        loader: "postcss-loader",
        options: {
            plugins: ["postcss-preset-env"],
        },
      },
      {loader: "stylus-native-loader", options: {}}
    ]
}
```

This yields the following error:
Error: postcss-preset-env is not a PostCSS plugin

The following documentation shows plugins being passed this way:

https://drive.google.com/file/d/1QqC-udnHzlgggW13J-UTayR1Z38UvOnu/view?usp=sharing

### 3. Using postcssOptions property to set postcss-preset-env yields a message

```
{
    test: /\.styl$/,
    use: [
      {loader: mini_css.loader},
      {loader: "css-loader"},
      {
        loader: "postcss-loader",
        options: {
          postcssOptions: {
            plugins: (_) => [  require("postcss-preset-env")() ],
          },
        },
      },
      {loader: "stylus-native-loader", options: {}}
    ]
}
```

This yields the following message:
You did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js.

The following documentation states plugins can be passed this way and provides an example of the method I used:

https://drive.google.com/file/d/1-KEAOuZNV7aKw8jv8ItoJ6feoPE3Hwqb/view?usp=sharing
https://drive.google.com/file/d/1INHxrkCmPF0KoQqugcbqMrEjAKQZl7Tu/view?usp=sharing

### How Do We Reproduce?

This webpack config file works if the postcss section is commented out.

[https://gist.github.com/michaelalhilly/ac711792ad256f4e7df17af6c5097b9c](url)

Any help would be appreciated.

**Comment by evilebottnawi** [comment]
In have `dev` branch in `master`, we prepare new major release, but got some problems and WIP on this, I apologize for the current situation, release will be in near future, please use this docs right now https://github.com/webpack-contrib/postcss-loader/tree/v3.0.0

**Comment by michaelalhilly** [comment]
No worries @evilebottnawi. This is not a critical part of the build process. I will keep an eye on this repo and try again when your team merges the update. Just thought it would be helpful to report this.

**Comment by evilebottnawi** [comment]
Done https://github.com/webpack-contrib/postcss-loader/releases/tag/v4.0.0, just use `^4.0.0` version for `postcss-loader`, docs up to day

**Comment by michaelalhilly** [comment]
@evilebottnawi Thanks for all your hard work!
