### ISSUE TITLE
options has an unknown property 'config'

### ISSUE THREAD

**Issue by in-in** [webpack-contrib/postcss-loader#472]
- Operating System: **Linux Mint 19.3**
- Node Version: **v12.15.0**
- NPM Version: **6.14.4**
- webpack Version: **4.44.1**
- postcss-loader Version: **4.0.0**

### Expected Behavior

Set custom config files

### Actual Behavior

```sh
ValidationError: Invalid options object. PostCSS Loader has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'config'. These properties are valid:
   object { postcssOptions?, execute?, sourceMap? }
```

### Code

```js
const style = {
  'test': /\.scss$/,
  'use': [
    'style-loader',
    {
      'loader': 'css-loader',
      'options': {
        'sourceMap': true,
      },
    },
    {
      'loader': 'postcss-loader',
      'options': {
        'config': path.resolve(PATHS.config, 'postcss.config.js'),
        'sourceMap': true,
      },
    },
    {
      'loader': 'sass-loader',
      'options': {
        'sourceMap': true,
      },
    },
  ],
};
```

According to the [documentation](https://github.com/webpack-contrib/postcss-loader/blob/master/README.md#string), the code above should work.

### How Do We Reproduce?
Try using the "config" option for postcss-loader

**Comment by equinusocio** [comment]
Same issue here. Our workflows are completely broken after this update.

**Comment by aariacarterweir** [comment]
Yup had to roll back to v3, this is broken in v4

**Comment by evilebottnawi** [comment]
Please read documentation and changelog before open the new issue:

```
const style = {
  'test': /\.scss$/,
  'use': [
    'style-loader',
    {
      'loader': 'css-loader',
      'options': {
        'sourceMap': true,
      },
    },
    {
      'loader': 'postcss-loader',
      'options': {
        'postcssOptions': {
          'config': path.resolve(PATHS.config, 'postcss.config.js'),
        },
        'sourceMap': true,
      },
    },
    {
      'loader': 'sass-loader',
      'options': {
        'sourceMap': true,
      },
    },
  ],
};
```

**Comment by in-in** [comment]
@evilebottnawi  please tell me who told you I didn't read the documentation?
Anyway, thank you for your help.

![202521599563397](https://user-images.githubusercontent.com/8797432/92469542-a49c6200-f1dd-11ea-99d1-be267165c7fe.png)

**Comment by evilebottnawi** [comment]
@in-in my mistake, sorry, WIP on updating docs

**Comment by evilebottnawi** [comment]
https://github.com/webpack-contrib/postcss-loader/pull/473

**Comment by equinusocio** [comment]
@evilebottnawi Next time, if 3 people share the same issue probably there is something better to say instead of "read the documentation" because you're assuming that 3 people are just stupid.

Said that, thanks for the fast update.

**Comment by evilebottnawi** [comment]
@equinusocio 
> Next time, as OOS developer, can i suggest that if 3 people share the same issue probably there is something better to say instead of "read the documentation" because you're assuming that 3 people are just stupid.

Unfortunately sometimes I get a lot more issues, because many developers don't like read notes, I can provide an infinite number of links to this :smile: Anyway I done mistake here

**Comment by Nux007** [comment]
> 
> 
> Please read documentation and changelog before open the new issue:
> 
> ```js
> const style = {
>   'test': /\.scss$/,
>   'use': [
>     'style-loader',
>     {
>       'loader': 'css-loader',
>       'options': {
>         'sourceMap': true,
>       },
>     },
>     {
>       'loader': 'postcss-loader',
>       'options': {
>         // All postcss options is now under `postcssOptions`
>         'postcssOptions': {
>           'config': path.resolve(PATHS.config, 'postcss.config.js'),
>         },
>         'sourceMap': true,
>       },
>     },
>     {
>       'loader': 'sass-loader',
>       'options': {
>         'sourceMap': true,
>       },
>     },
>   ],
> };
> ```

Thank's :-)

**Comment by imadarif** [comment]
After updating postcssOptions i got javascript heap memory error
