### ISSUE TITLE
4.0.0 and resolve-url-loader no longer work together

### ISSUE THREAD

**Issue by TheDutchCoder** [webpack-contrib/postcss-loader#477]
- Operating System: MacOS 10.14.6
- Node Version: 12.15.0
- NPM Version: 6.14.8
- webpack Version: 4.44.1
- postcss-loader Version: 4.0.0

### Expected Behavior
The build to pass without errors

### Actual Behavior
Build fails because of postcss-loader requiring absolute URL's, but resolve-url-loader passes down relative URLs (I think)

### Code

```js
// webpack.config.js (partial)
...
      use: [
        MiniCssExtractPlugin.loader,
        {
          loader: 'css-loader',
          options: {
            importLoaders: 2,
            sourceMap: true,
          },
        },
        {
          loader: 'resolve-url-loader',
        },
        {
          loader: 'postcss-loader',
          options: {
            sourceMap: true,
          },
        },
      ],
```

### How Do We Reproduce?
I can't share my private repo for this, but I can reproduce the issue by downgrading to v3 (where the build is successful).

**Comment by evilebottnawi** [comment]
`postcss-loader` does not resolve `URLs`, `css-loader` resolve all URLs starts with `/` as server-relative URLs, exactly how they work in the browser, you don't need `resolve-url-loader` loader anymore

**Comment by TheDutchCoder** [comment]
Removing `resolve-url-loader` results in resolving errors like: `Error: Can't resolve './src/fonts/Miller-Banner-Light.woff2' in '/var/projects/foo/webpack/src/css'`

**Comment by TheDutchCoder** [comment]
Ohhhh hold on... it's not resolving URL's in the webpack config. Not so much in the files.
Okay I'll take a look at that. The error was very ambiguous unfortunately.
