### ISSUE TITLE
postcss-load-config

### ISSUE THREAD

**Issue by RyanZim** [webpack-contrib/postcss-loader#480]
Hi, I'm @RyanZim, maintainer of https://github.com/postcss/postcss-cli

I noticed that in https://github.com/webpack-contrib/postcss-loader/pull/440, you migrated away from https://github.com/michael-ciniawsky/postcss-load-config in favour of doing the config loading internally. I'm curious as to why this was done. postcss-cli still uses postcss-load-config; should we be migrating away from it?

**Comment by evilebottnawi** [comment]
We had a discussion yesterday with @ai and decided to create an RFC for configurations, let's wait

**Comment by evilebottnawi** [comment]
@RyanZim fixed https://github.com/michael-ciniawsky/postcss-load-config/compare/v2.1.0...v2.1.1?

**Comment by RyanZim** [comment]
@evilebottnawi Yeah, `postcss-load-config` now supports postcss v8; was that the only reason you switched away from it?

**Comment by evilebottnawi** [comment]
@RyanZim Reasons:
- old version `cosmiconfig` (memory leak)
- object syntax is very misleading, no one tool (babel/remark/etc) do not use `object` syntax, example: `{ "plugin-name": false}`, plugin can accept `false` as options, but in this case we disable this plugin
- you can't use `{ require.resolve("my-plugin"): options }`
- you can't use plugins twice `{ "plugin-name": { "color": "red" }, "plugin-name": { "color": "blue" } }`
- no fixes/features a lot of time (looks abandoned)
-

**Comment by evilebottnawi** [comment]
Let's close, feel free to feedback

**Comment by RyanZim** [comment]
Oh, yes, forgot about this issue; sorry.
