### ISSUE TITLE
Migrating `options.config.ctx` values to v4 equivalent

### ISSUE THREAD

**Issue by illepic** [webpack-contrib/postcss-loader#484]
Documentation Is:

- [ x] Missing
- [ ] Needed
- [ ] Confusing
- [ ] Not Sure?

### Please Explain in Detail...

With `options.config.ctx` being removed in `v4`, there is no documentation on migrating arbitrary variables to the new approach in `v4`.

### Your Proposal for Changes

I'm still trying to solve this, but happy to PR documentation changes when I figure it out.

**Comment by evilebottnawi** [comment]
No migrations, this features is not supported anymore due caching problems, if you want to add a specific parameter to `api` please open new issue and describe why you need this
