### ISSUE TITLE
postcss-loader says "no plugin set" in 4.0.2 but not in 3.0.0

### ISSUE THREAD

**Issue by TorRanfelt** [webpack-contrib/postcss-loader#487]
postcss-loader 4.0.2 tells me I didn't set any plugin even though autoprefixer has been set.

Because my build file is used across multiple projects autoprefixer is in another library. This was not a problem with postcss-loader 3.0.0, but searching the net I've come across multiple mentions of this being an issue.

If require does not work with plugins in postcss-loader then it is the exception among the many packages I use with webpack.

```
const projectPath = (subpath) => path.resolve(projectDir + '/' + subpath);
const projectRequire = (subpath) => require(projectPath('node_modules/' + subpath));
```

```
                            loader: 'postcss-loader',
                            options: {
                                postcssOptions: {
                                    plugins: function () {
                                        return [
                                            projectRequire('autoprefixer')
                                        ];
                                    }
                                }
                            }
```

The warning: "You did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js."

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue template It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

**Comment by evilebottnawi** [comment]
Respect time of other developers

**Comment by TorRanfelt** [comment]
Fair enough.

If someone else who has the same issue comes across this:
It's because postcss-loader now is able to reference a plugin like you normally would with a loader, and hence no longer needs  special care if your script is in another library than the one containing node_modules.

This works.
```
                            loader: 'postcss-loader',
                            options: {
                                postcssOptions: {
                                    plugins: [
                                        [
                                            'autoprefixer'
                                        ]
                                    ]
                                }
                            }
```
