### ISSUE TITLE
Doc for webpack v4 at https://v4.webpack.js.org/loaders/postcss-loader/ is incorrect

### ISSUE THREAD

**Issue by nolimitdev** [webpack-contrib/postcss-loader#495]
Documentation Is:

- [ ] Missing
- [ ] Needed
- [x] Confusing
- [ ] Not Sure?

### Please Explain in Detail...
Doc for your loader for webpack v4 is here https://v4.webpack.js.org/loaders/postcss-loader/ and there is a example which is not working... It is first after Plugins header here: https://v4.webpack.js.org/loaders/postcss-loader/#plugins

1.) It seems that "ident" options is not supported for ages (since webpack v2.2.1 see migration guide: https://webpack.js.org/migrate/3/#complex-options)

2.) Function alternative `plugins: (loader) => ...` seems to be not working any more (I think that it is what was reported here: https://github.com/webpack-contrib/postcss-loader/issues/494)

3.) Scheme `options: { ident : ..., plugins: ... }` is incorrect because of error: 
>  options has an unknown property 'plugins'. These properties are valid: object { postcssOptions?, execute?, sourceMap? }

... so `plugins` must be inside `postcssOptions` by my testing

### Your Proposal for Changes
It should be fixed, but Im note sure where is a repo/branch for postcss-loader website https://v4.webpack.js.org/loaders/postcss-loader/

**Comment by evilebottnawi** [comment]
Because here docs for v4 version, v4 is deprecated and docs will not updated, sorry, we can't keep up to deps all docs, include old versions

**Comment by nolimitdev** [comment]
It seems that doc for v4 is incorrect for ages before v5. I could make PR but I can not find branch for v4. Webpack v5 was released fee days ago, I dont think it is deprecated... https://webpack.js.org/blog/2020-10-10-webpack-5-release/ 

> So today (2020-10-10) webpack 5.0.0 is released, but this doesn't mean it's done, bugfree or even feature-complete. As with webpack 4 we continue development by fixing problems and adding features. In the next days there will probably be a lot bugfixes. Features will come later.

**Comment by evilebottnawi** [comment]
You can open an issue in webpack docs repo, we can't fix it here

**Comment by nolimitdev** [comment]
Sorry for maybe silly questions and thanks for patience, but I was reporting it here because of website https://v4.webpack.js.org/loaders/postcss-loader/ has at the top feature "EDIT DOCUMENT" and it navigates to this repo where Im reporting it ;) Im really confused now. So if this repo is not correct could you please provide some link where I can report it?
![link](https://user-images.githubusercontent.com/25459317/96465087-dbc45100-1228-11eb-9ccd-2315ce91eda7.png)

**Comment by evilebottnawi** [comment]
This problem with not docs, this problem is how official docs site stores loaders/plugins docs for old versions
