### ISSUE TITLE
Accessing the loader in postcss-loader 4.x

### ISSUE THREAD

**Issue by jantimon** [webpack-contrib/postcss-loader#496]
Is there a migration guide for users migrating postcss-loader 3.x to postcss-loader 4.x?
 
I couldn't find the correct way to access the `loader` with postcss-loader 4.x.

With postcss-loader 3.x my configuration looked like this:

```js
loader: 'postcss-loader',
  options: {
    plugins: (loader) => [
      new IconfontWebpackPlugin(loader)
    ]
}
```

How would the configuration look like for postcss-loader 4.x?

This is the full demonstration of the example above: https://codesandbox.io/s/icon-font-webpack-plugin-ku3qz?file=/webpack.config.js

**Comment by evilebottnawi** [comment]
Here migration guide https://github.com/webpack-contrib/postcss-loader/releases/tag/v4.0.0

> PostCSS (plugins/syntax/parser/stringifier) options was moved to the postcssOptions option, please look at docs


https://github.com/webpack-contrib/postcss-loader#postcssoptions
