### ISSUE TITLE
Allow ident to be passed to loader options

### ISSUE THREAD

**Issue by fa93hws** [webpack-contrib/postcss-loader#516]
### Expected Behavior / Situation
`ident` can be passed to loader option

### Actual Behavior / Situation
It is removed in webpack-contrib/postcss-loader@962b1d6#diff-bce88eb40f042401d096992738d1ffa448830370e2e797514de95284d541b3f0

### Modification Proposal
Hi we want to stablize the indent because we use webpack's `loader-runner` to preprocessing some of our css resources. As a consequence, we would like a constant, configurable ident instead of something random.
Also I think it's harmless to have that available in option as well?

**Comment by alexander-akait** [comment]
You don't need `ident`, also you can set it on loader level:
```
{
  ident: 'ident',
  loader: 'postcss-loader'
}
```
