### ISSUE TITLE
I get the following message

### ISSUE THREAD

**Issue by arman-mukatov** [webpack-contrib/postcss-loader#521]
ERROR in ./src/containers/SupportPage/SupportInner.less
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleError: Module Error (from ./node_modules/postcss-loader/dist/cjs.js):
Loading PostCSS "postcss-import" plugin failed: The "path" argument must be of type string. Received undefined

(@/project/src/containers/SupportPage/SupportInner.less)
    at Object.emitError (/project/node_modules/webpack/lib/NormalModule.js:524:6)
    at getPostcssOptions (/project/node_modules/postcss-loader/dist/utils.js:222:19)
    at Object.loader (/project/node_modules/postcss-loader/dist/index.js:57:42)
 @ ./src/containers/SupportPage/SupportInner.js 9:0-50 88:17-40 90:17-41 92:17-41 98:66-88 105:17-42 112:21-46 117:21-45 119:21-43
 @ ./src/containers/SupportPage/Loadable.js 108:13-50 81:21-85:3
 @ ./src/routes.js 6:0-82 40:15-26 43:15-31
 @ ./src/client.js 17:0-28 86:30-36

webpack-5.28.0
postcss-8.2.8
postcss-import-14.0.0
postcss-loader-5.2.0
postcss-preset-env-6.7.0

postcss.config.js

```
module.exports = ({ file }) => ({
    plugins: {
      'postcss-import': {
        root: file.dirname
      },
      'postcss-url': [
        {
          filter: './**.*',
          url: asset => `./${asset.url}`
        },
      ],
      'postcss-preset-env': {
        stage: 3,
        browsers: 'last 2 version',
      },
      'postcss-browser-reporter': {},
      'postcss-reporter': {},
      'cssnano': {},
    }
});
```
webpack config:

```
{
        test: /\.less$/,
        use: [
          {
            loader: MiniCssExtractPlugin.loader
          },
          {
            loader: 'css-loader',
            options: {
              modules: {
                localIdentName: 'k_[hash:base64:5]'
              },
              importLoaders: 2,
              sourceMap: true
            }
          },
          {
            loader: 'postcss-loader',
            options: {
              sourceMap: true
            }
          },
          {
            loader: 'less-loader'
          }
        ]
      },
```

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

Bug in `postcss-import`, please read message
