### ISSUE TITLE
[Security Risk] Update cssnano to ^4.1.11

### ISSUE THREAD

**Issue by bymattoa** [webpack-contrib/postcss-loader#523]
Attempted to raise a PR myself, but not have permissions to push to this repo.

- Operating System: n/a
- Node Version:
- NPM Version:
- webpack Version: 
- postcss-loader Version: all

### Expected Behavior / Situation

`postcss-loader` has a transitive dependency on `is-svg` `^3.0.0` through `cssnano` `^4.1.10`. This version contains a security risk for ReDoS attacks:

https://github.com/advisories/GHSA-7r28-3m3f-r2pr

### Actual Behavior / Situation

n/a

### Modification Proposal

Update `cssnano` to `^4.1.11`. This will version removes the dependency on `is-svg`. 

```
"cssnano": "^4.1.11",
```

**Comment by alexander-akait** [comment]
We don't have `cssnano` in deps, please do it locally https://github.com/webpack-contrib/postcss-loader/blob/master/package.json#L44
