### ISSUE TITLE
Remove postcss-preset-env from the docs

### ISSUE THREAD

**Issue by HerrZatacke** [webpack-contrib/postcss-loader#534]
Documentation Is:

- [ ] Missing
- [ ] Needed
- [x] Confusing
- [ ] Not Sure?

### Please Explain in Detail...
the package postcss-preset-env seems not to be maintained anymore
https://github.com/csstools/postcss-preset-env/issues/205
And it introduces a high severity security issue:
https://github.com/advisories/GHSA-7p7h-4mm5-852v
https://github.com/csstools/postcss-preset-env/issues/209
https://github.com/csstools/postcss-preset-env/issues/203

### Your Proposal for Changes
Remove reference/recommendation to use postcss-preset-env as it might lead new/unexperienced users to still use/trust this package and lead people to ignore security advisories altogether.

**Comment by alexander-akait** [comment]
`postcss-preset-env` is still in WIP on migration on PostCSS v8, please be patient

**Comment by paulius-valiunas** [comment]
there hasn't been a single commit on their repository for over a year...

**Comment by cyfung1031** [comment]
> there hasn't been a single commit on their repository for over a year...

see  https://github.com/csstools/postcss-preset-env/issues/191
As the maintainer is said something in June this year, someone might help for the update now.
