### ISSUE TITLE
Version-4 dependencies update

### ISSUE THREAD

**Issue by WraithKenny** [webpack-contrib/postcss-loader#535]
PostCSS dependency is outdated on the `version-4` branch, and `npm audit` complains. (It was updated on the master/v6)

- Operating System: MacOS
- Node Version: v16.3.0
- NPM Version: 7.17.0
- webpack Version: ^4.46.0
- postcss-loader Version: ^4.3.0

### Expected Behavior
`npm audit` wouldn't complain

### Actual Behavior
`npm audit` complains

### How Do We Reproduce?
`npm audit`

Just need to update the `postcss` dependency on the version-4 branch and publish.

**Comment by alexander-akait** [comment]
Please update your deps locally, we use `^` for our dependencies, so you can update your deps without any problems
