### ISSUE TITLE
Samples how to create plugin for additional dependencies are deprecated

### ISSUE THREAD

**Issue by nolimitdev** [webpack-contrib/postcss-loader#552]
Documentation Is:

- [x] Deprecated

### Please Explain in Detail...

Samples here https://github.com/webpack-contrib/postcss-loader#add-dependencies-contextdependencies-builddependencies-missingdependencies how to create plugin are deprecated. 

### Your Proposal for Changes
Code `postcss.plugin("...", ...)` should be updated https://evilmartians.com/chronicles/postcss-8-plugin-migration or if it is interesting for you, plugin [postcss-add-dependencies](https://www.npmjs.com/package/postcss-add-dependencies) to solve this easily (oneliner) can be linked

**Comment by alexander-akait** [comment]
Yep, PR welcome :+1:

**Comment by alexander-akait** [comment]
Fixed
