### ISSUE TITLE
Security vulnerability affecting all versions

### ISSUE THREAD

**Issue by migill** [webpack-contrib/postcss-loader#570]
A security vulnerability in postcss-loader has been identified by synk.io (see https://security.snyk.io/vuln/SNYK-JS-POSTLOADER-2403737).

**Comment by alexander-akait** [comment]
We `postcss-loader`, you provide link on `post-loader`, it is diffident package

**Comment by alexander-akait** [comment]
Can you show a message?

**Comment by alexander-akait** [comment]
Can you write `npm ls postcss-loader` and `npm ls post-loader`?

**Comment by ansib** [comment]
Could it be possible, that it was incorrectly assigned to this package (npm and JFrog XRay)?

Here is the correct link to Snyk:
[https://security.snyk.io/vuln/SNYK-JS-POSTLOADER-2403737](https://security.snyk.io/vuln/SNYK-JS-POSTLOADER-2403737)

**Comment by alexander-akait** [comment]
You should update postcss-loader to https://github.com/webpack-contrib/postcss-loader/blob/master/package.json#L3, maybe even open an issue in angular cli

**Comment by ansib** [comment]
Yes we also need to do this. But version 6.2.1 is also blocked by jfrog and npm audit. I will open an issue at angular cli to address this incorrect vulnerability.
