### ISSUE TITLE
autoprefixer: Replace color-adjust to print-color-adjust. The color-adjust shorthand is currently deprecated

### ISSUE THREAD

**Issue by liuchuancong** [webpack-contrib/postcss-loader#590]
```
"postcss-loader": "^7.0.0",
```
How can i fix this problem?

console warning
```
autoprefixer: Replace color-adjust to print-color-adjust. The color-adjust shorthand is currently deprecated
```

**Comment by alexander-akait** [comment]
Please follow the warning mesage and change `color-adjust` on `print-color-adjust` in yout source code

**Comment by alexander-akait** [comment]
@ktsangop `autoprefixer` is not dependecy of `postcss-loader`, angular CLI uses this plugin, if you got this warning it means you have `color-adjust` in your source code (you have code in your dependecies check it, also other plugins before autoprefixer can generate code and late postcss throw a warning on code, double check it)

**Comment by ktsangop** [comment]
@alexander-akait sorry that was my bad I misread the `yarn why` output. 
The package that depends on `autoprefixer` is `postcss-preset-env` which does have the deprecated `color-adjust`.
