### ISSUE TITLE
Invalid default specified for postcssOptions.config

### ISSUE THREAD

**Issue by Knagis** [webpack-contrib/postcss-loader#626]
Documentation Is:

https://github.com/webpack-contrib/postcss-loader#config

- [ ] Missing
- [ ] Needed
- [X] Confusing
- [ ] Not Sure?

### Please Explain in Detail...

https://github.com/webpack-contrib/postcss-loader#config specifies the default is `undefined` which isn't really true - if the value is `undefined` then https://github.com/webpack-contrib/postcss-loader/blob/master/src/index.js#L40 assumes `true`.

### Your Proposal for Changes

Change the default in documentation from `undefined` to `true`

**Comment by Knagis** [comment]
I would also suggest to highlight a recommendation to set `postcssOptions` in webpack config with `config: false` as a performance optimization. In one of my builds it seems doing this has helped me to decrease build time from 42->38 seconds (~10k TS and PostCSS modules). My postcss config was rather heavy (a func, not just an object, plugin factory, not plugin instances etc.).

**Comment by alexander-akait** [comment]
Hello, yes, you are right, let's do it, do you want to send a PR?

**Comment by Knagis** [comment]
PR created: #627
