### ISSUE TITLE
Peer dependencies for cosmiconfig-typescript-loader not met

### ISSUE THREAD

**Issue by mdrodz** [webpack-contrib/postcss-loader#637]
### Bug report

postcss-loader doesn't provide @types/node, ts-node and typescript, requested by "cosmiconfig-typescript-loader"

### Actual Behavior

This breaks PnP for Yarn

### Expected Behavior

postcss-loader should include these packs as dependencies since it is requested by a package it uses

### How Do We Reproduce?

Using Yarn v2 PnP, install the package and the warning will appear

**Comment by alexander-akait** [comment]
Please look at https://github.com/webpack-contrib/postcss-loader/releases/tag/v7.2.1

**Comment by alexander-akait** [comment]
We don't use `ts-node` directly so we should not provide peer deps in the package

**Comment by mdrodz** [comment]
Maybe this is a bug with the cosmiconfig-typescript-loader package.json then?

Because it states that it needs a ts-node in the environment (peer deps).

Also, even with the latest patch (7.2.1), I still have the same errors:

<img width="727" alt="Yarn v2 pnp error" src="https://user-images.githubusercontent.com/20651545/229610720-c89f201a-88af-4d47-aa81-7a531f05e1ae.png">

**Comment by alexander-akait** [comment]
npm v7.2.1, but the latest version is https://github.com/npm/cli/releases/tag/v9.6.3

**Comment by alexander-akait** [comment]
What is yarn version?

**Comment by mdrodz** [comment]
Yarn version is 3.5.0

**Comment by alexander-akait** [comment]
Looks like bug is there https://github.com/Codex-/cosmiconfig-typescript-loader/blob/main/package.json#L36, they should be optinal

**Comment by alexander-akait** [comment]
I can't add them as `dependecies`, because we don't use it directly, putting them in peer deps doesn't solve nothing...

**Comment by mdrodz** [comment]
Yup, it seems to be their problem:

https://github.com/Codex-/cosmiconfig-typescript-loader/issues/79

Thanks!
