### ISSUE TITLE
ERROR in ./src/assets/css/flaticon-set.css (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[2]!./node_modules/source-map-loader/dist/cjs.js!./src/assets/css/flaticon-set.css) 9:36-78

### ISSUE THREAD

**Issue by raphaeledgar** [webpack-contrib/postcss-loader#668]
ERROR in ./src/assets/css/flaticon-set.css (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[2]!./node_modules/source-map-loader/dist/cjs.js!./src/assets/css/flaticon-set.css) 9:36-78

Module not found: Error: Can't resolve './flaticon.svg' in 'F:\work2\noa-portfolio\myportfolio\src\assets\css'

I don't understand above issue.
Also, there are several issues like:
ERROR in ./src/assets/fonts/remixicon.css (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[2]!./node_modules/source-map-loader/dist/cjs.js!./src/assets/fonts/remixicon.css) 5:36-93
Module not found: Error: Can't resolve 'remixicon.eot?t=1590207869815' in 'F:\work2\noa-portfolio\myportfolio\src\assets\fonts'

ERROR in ./src/assets/fonts/remixicon.css (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[2]!./node_modules/source-map-loader/dist/cjs.js!./src/assets/fonts/remixicon.css) 6:36-95
Module not found: Error: Can't resolve 'remixicon.woff2?t=1590207869815' in 'F:\work2\noa-portfolio\myportfolio\src\assets\fonts'

Please help me!!!

**Comment by alexander-akait** [comment]
It means you have `url(./flaticon.svg)` in your CSS file but don't have `flaticon.svg` file, you can put it there or use https://webpack.js.org/configuration/resolve/ to provide alternative file or you can just ignore this URL using https://github.com/webpack-contrib/css-loader#url
