### ISSUE TITLE
Remove `webpack` from `peerDependencies`

### ISSUE THREAD

**Issue by feedm3** [webpack-contrib/postcss-loader#678]
### Modification Proposal

We are using `postcss-loader` with `rsbuild`. This means, we don't use webpack directly anymore / don't have it installed. `postcss-loader` still works fine with the setup, but when doing a `yarn install`, yarn complains about not having `webpack` listed in our dependencies.

> ➤ YN0002: │ my-awesome-rsbuild-webapp doesn't provide webpack (p1ea2d), requested by postcss-loader.

As `postcss-loader` doesn't use `webpack` directly, I think it's ok to just remove it from the `peerDependencies` array.

### Expected Behavior / Situation

The loader will behave the same, but in the context of `rsbuild` won't add a warning in the install logs.

### Actual Behavior / Situation

A warning in the install logs:

> ➤ YN0002: │ my-awesome-rsbuild-webapp doesn't provide webpack (p1ea2d), requested by postcss-loader.

**Comment by alexander-akait** [comment]
https://github.com/webpack-contrib/css-loader/issues/1567#issuecomment-1911926011
